"""
Self-improvement engine for APIS.
Generates code, validates it, deploys it, and learns from results.
"""
import logging
import re
import json
from typing import List, Dict, Optional, Any, Tuple
from datetime import datetime

from self_improve.knowledge_base import KnowledgeBase as OldKnowledgeBase
from self_improve.metrics_analyzer import MetricsAnalyzer
from self_improve.auto_deploy import AutoDeployer
from utils.discord_notifier import DiscordNotifier
from config.patterns import KeyClassifier, PATTERNS
from core.knowledge_base import KnowledgeBase as CeoKnowledgeBase
from pathlib import Path
import os

logger = logging.getLogger(__name__)


class CodeGenerator:
    """
    Generates Python code based on natural language descriptions.
    Uses template-based generation for reliability.
    """

    # Templates for common code generation tasks
    SCANNER_TEMPLATE = '''"""
{scanner_name} scanner for APIS.
Auto-generated by the self-improvement engine.
"""
import logging
from typing import List, Dict, Optional
from scanners.base_scanner import BaseScanner, ScanResult

logger = logging.getLogger(__name__)


class {class_name}(BaseScanner):
    """Auto-generated scanner for {scanner_name}."""

    def __init__(self, enabled: bool = True):
        super().__init__("{scanner_name}", enabled)

    def scan(self) -> ScanResult:
        """Scan {scanner_name} for exposed keys."""
        raw_data: List[str] = []
        metadata: Dict = {{"scanner": "{scanner_name}", "items_found": 0}}

        # TODO: Implement scanning logic
        # This scanner was auto-generated and needs implementation

        return ScanResult(
            scanner_name=self.name,
            source="{scanner_name}",
            raw_data=raw_data,
            metadata=metadata,
        )
'''

    PATTERN_TEMPLATE = '''# Pattern for {key_type}
# Auto-generated by self-improvement engine
("{key_type}", r"{pattern}", "{description}", "{prefix}"),
'''

    VALIDATOR_TEMPLATE = '''    "{key_type}": {{"min_len": {min_len}, "max_len": {max_len}, "prefix": "{prefix}"}},'''

    def __init__(self, notifier: Optional[DiscordNotifier] = None):
        self.notifier = notifier or DiscordNotifier()
        self.classifier = KeyClassifier()

    def generate_feature(self, description: str) -> Tuple[str, str]:
        """
        Generate Python code based on a natural language description.

        Args:
            description: Natural language description of the feature.

        Returns:
            Tuple of (generated_code, filename).
        """
        desc_lower = description.lower()

        # Determine what type of feature to generate
        if "scanner" in desc_lower or "scan" in desc_lower:
            return self._generate_scanner(description)
        elif "pattern" in desc_lower or "detect" in desc_lower or "classif" in desc_lower:
            return self._generate_pattern(description)
        elif "validator" in desc_lower or "valid" in desc_lower:
            return self._generate_validator(description)
        elif "notifier" in desc_lower or "report" in desc_lower:
            return self._generate_notifier(description)
        else:
            return self._generate_generic(description)

    def _generate_scanner(self, description: str) -> Tuple[str, str]:
        """Generate a new scanner module."""
        # Extract scanner name from description
        words = description.lower().split()
        scanner_name = "custom"
        for word in words:
            if word in ("for", "scanner", "scan", "new"):
                continue
            scanner_name = word
            break

        class_name = scanner_name.title().replace("_", "") + "Scanner"
        filename = f"{scanner_name}_scanner.py"

        code = self.SCANNER_TEMPLATE.format(
            scanner_name=scanner_name,
            class_name=class_name,
        )

        return code, filename

    def _generate_pattern(self, description: str) -> Tuple[str, str]:
        """Generate a new key classification pattern."""
        # Try to extract key type and pattern from description
        key_type = "unknown"
        pattern = "xox[baprs]-[a-zA-Z0-9-]{10,}"
        description_text = "Auto-generated pattern"
        prefix = "[redacted]"

        # Look for key type in description
        type_keywords = {
            "slack": ("slack", "xox[baprs]-[a-zA-Z0-9-]{10,}", "Slack token", "xox"),
            "aws": ("aws", "AKIA[0-9A-Z]{16}", "AWS Access Key ID", "AKIA"),
            "google": ("google", "AIza[0-9A-Za-z_-]{35}", "Google API key", "AIza"),
            "openai": ("openai", "sk-[a-zA-Z0-9]{20,}", "OpenAI API key", "sk-"),
            "claude": ("claude", "sk-ant-[a-zA-Z0-9_-]{20,}", "Anthropic/Claude API key", "sk-ant-"),
            "stripe": ("stripe", "sk_live_[a-zA-Z0-9]{24,}", "Stripe secret key", "sk_live_"),
            "discord": ("discord", r"[\w-]{24}\.[\w-]{6}\.[\w-]{27}", "Discord bot token", "[redacted]"),
        }

        desc_lower = description.lower()
        for keyword, (kt, pat, desc, pre) in type_keywords.items():
            if keyword in desc_lower:
                key_type = kt
                pattern = pat
                description_text = desc
                prefix = pre
                break

        # Generate pattern code
        code = self.PATTERN_TEMPLATE.format(
            key_type=key_type,
            pattern=pattern,
            description=description_text,
            prefix=prefix,
        )

        return code, f"{key_type}_pattern.py"

    def _generate_validator(self, description: str) -> Tuple[str, str]:
        """Generate a new validation rule."""
        key_type = "unknown"
        min_len = 20
        max_len = 200
        prefix = "sk-"

        desc_lower = description.lower()
        if "slack" in desc_lower:
            key_type, min_len, max_len, prefix = "slack", 10, 200, "xox"
        elif "aws" in desc_lower:
            key_type, min_len, max_len, prefix = "aws", 20, 20, "AKIA"
        elif "discord" in desc_lower:
            key_type, min_len, max_len, prefix = "discord", 59, 80, "None"

        code = self.VALIDATOR_TEMPLATE.format(
            key_type=key_type,
            min_len=min_len,
            max_len=max_len,
            prefix=prefix,
        )

        return code, f"{key_type}_validator.py"

    def _generate_notifier(self, description: str) -> Tuple[str, str]:
        """Generate a new notification method."""
        code = '''    def send_custom_report(self, title: str, data: List[Dict]) -> bool:
        """Send a custom report to Discord."""
        embeds = [{
            "title": title,
            "fields": [{"name": str(k), "value": str(v), "inline": False} for k, v in data.items()],
            "color": 0x5865F2,
        }]
        return self._send(title, embeds)
'''
        return code, "custom_notifier.py"

    def _generate_generic(self, description: str) -> Tuple[str, str]:
        """Generate a generic utility module."""
        code = f'''"""
Auto-generated module for: {description}
Generated by APIS self-improvement engine.
"""
import logging
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


class AutoGeneratedFeature:
    """Auto-generated feature for: {description}"""

    def __init__(self):
        self.description = "{description}"

    def execute(self, data: List[Dict]) -> List[Dict]:
        """Execute the auto-generated feature."""
        logger.info(f"Executing auto-generated feature: {{self.description}}")
        return data
'''
        return code, "auto_generated.py"


class SelfImprovementEngine:
    """
    Main self-improvement engine for APIS.

    Responsibilities:
    - Analyze scan results and metrics
    - Identify areas for improvement
    - Generate code to address gaps
    - Validate and deploy generated code
    - Learn from results and adjust priorities
    - Communicate with Discord for status and help requests
    """

    # Threshold for triggering new pattern generation
    UNCLASSIFIED_THRESHOLD = 3
    # Minimum confidence for auto-deploying without human confirmation
    AUTO_DEPLOY_CONFIDENCE = 0.9

    def __init__(self, engine: Any = None):
        self.engine = engine
        self.kb = OldKnowledgeBase()
        # Use CEO KnowledgeBase for duplicate detection if available
        self.ceo_kb = CeoKnowledgeBase()
        self.analyzer = MetricsAnalyzer(self.kb)
        self.deployer = AutoDeployer()
        self.generator = CodeGenerator(
            engine.notifier if engine else None
        )
        self.notifier = self.generator.notifier
        self._improvement_queue: List[Dict] = []
        self._last_analysis: Optional[Dict] = None
        self._generated_this_session: set = set()  # Track in-memory to prevent double-gen

    def learn_from_results(self, keys: List[Dict], scan_results: List) -> None:
        """
        Learn from scan results and update knowledge base.

        Args:
            keys: List of classified key dicts.
            scan_results: List of ScanResult objects.
        """
        try:
            analysis = self.analyzer.analyze_results(keys, scan_results)
            self._last_analysis = analysis

            # Check for unclassified keys
            unclassified = [k for k in keys if k.get("type") == "generic"]
            if len(unclassified) >= self.UNCLASSIFIED_THRESHOLD:
                self._handle_unclassified_keys(unclassified)

            # Check for new key types
            for key_type in analysis.get("new_key_types", []):
                self.notifier.send_new_key_type(
                    key_type,
                    unclassified[0].get("masked_value", "") if unclassified else "",
                    confidence=0.5,
                )

            # Update knowledge base with patterns
            for pattern in self.kb.get_patterns():
                self.classifier_add_pattern(pattern)

        except Exception as e:
            logger.error(f"Error in learn_from_results: {e}")

    def classifier_add_pattern(self, pattern: Dict) -> None:
        """Add a pattern from knowledge base to the classifier."""
        try:
            self.generator.classifier.add_pattern(
                name=pattern["name"],
                pattern=pattern["pattern"],
                description=pattern.get("description", ""),
                prefix=pattern.get("prefix", "[redacted]"),
            )
        except Exception:
            pass

    def _handle_unclassified_keys(self, unclassified_keys: List[Dict]) -> None:
        """Handle keys that couldn't be classified."""
        self.notifier.send_info(
            f"⚠️ Found {len(unclassified_keys)} unclassified keys. "
            f"Analyzing patterns..."
        )

        # Try to identify a pattern from the unclassified keys
        pattern = self._identify_pattern(unclassified_keys)
        if pattern:
            key_type = pattern.get("type", "unknown")
            self.notifier.send_new_key_type(
                key_type,
                unclassified_keys[0].get("masked_value", ""),
                confidence=pattern.get("confidence", 0.0),
            )

            # Add to improvement queue
            self._improvement_queue.append({
                "type": "new_pattern",
                "key_type": key_type,
                "pattern": pattern.get("pattern", ""),
                "description": pattern.get("description", ""),
                "priority": "high",
            })

    def _identify_pattern(self, keys: List[Dict]) -> Optional[Dict]:
        """Try to identify a pattern from unclassified keys."""
        if not keys:
            return None

        # Look for common prefixes
        prefixes = {}
        for key in keys:
            value = key.get("value", "")
            if len(value) >= 4:
                prefix = value[:4]
                prefixes[prefix] = prefixes.get(prefix, 0) + 1

        # Find the most common prefix
        if prefixes:
            best_prefix = max(prefixes, key=prefixes.get)
            if prefixes[best_prefix] >= 2:
                # Generate a regex pattern
                return {
                    "type": f"custom_{best_prefix.lower()}",
                    "pattern": re.escape(best_prefix) + r"[a-zA-Z0-9_-]{10,}",
                    "description": f"Auto-detected pattern with prefix '{best_prefix}'",
                    "prefix": best_prefix,
                    "confidence": min(prefixes[best_prefix] / len(keys), 1.0),
                }

        return None

    def check_for_improvements(self) -> None:
        """Check for and execute improvement opportunities."""
        if not self._last_analysis:
            return

        opportunities = self._last_analysis.get("improvement_opportunities", [])

        for opp in opportunities:
            if opp["type"] == "new_pattern":
                self._generate_and_deploy_pattern(opp)
            elif opp["type"] == "scanner_optimization":
                self._generate_and_deploy_scanner(opp)
            elif opp["type"] == "validation_improvement":
                self._generate_and_deploy_validator(opp)

    def _generate_and_deploy_pattern(self, opportunity: Dict) -> None:
        """Generate and deploy a new pattern."""
        description = opportunity.get("description", "Add new key pattern")
        self.notifier.send_self_improvement(
            f"Identified: {description}. Generating pattern...",
            success=True,
        )

        code, filename = self.generator.generate_feature(description)

        # For patterns, update the patterns.py file directly
        if "pattern" in filename:
            success, msg = self._deploy_pattern(opportunity)
        else:
            success, msg = self.deployer.deploy_code(code, filename)

        self.analyzer.record_code_generation(success)

        if success:
            self.notifier.send_self_improvement(
                f"New pattern deployed: {msg}",
                success=True,
            )
            self.kb.add_improvement(
                feature=f"Added pattern for {description}",
                code_changed="config/patterns.py",
                success=True,
                details=msg,
            )
        else:
            self.notifier.send_self_improvement(
                f"Pattern deployment failed: {msg}",
                success=False,
            )
            self.kb.add_failed_attempt(
                feature=f"Pattern for {description}",
                error=msg,
            )

    def _deploy_pattern(self, opportunity: Dict) -> Tuple[bool, str]:
        """Deploy a new pattern to patterns.py."""
        # Try to extract pattern info from the opportunity
        desc = opportunity.get("description", "")
        key_type = "custom"
        pattern = r"[a-zA-Z0-9_-]{20,}"
        description = "Auto-generated pattern"
        prefix = "[redacted]"

        # Map description to known patterns
        desc_lower = desc.lower()
        if "slack" in desc_lower:
            key_type, pattern, description, prefix = "slack", "xox[baprs]-[a-zA-Z0-9-]{10,}", "Slack token", "xox"
        elif "aws" in desc_lower:
            key_type, pattern, description, prefix = "aws", "AKIA[0-9A-Z]{16}", "AWS Access Key ID", "AKIA"

        return self.deployer.update_pattern_file(
            pattern_name=key_type,
            pattern=pattern,
            description=description,
            prefix=prefix,
        )

    def _should_generate_scanner(self, description: str, filename: str) -> Tuple[bool, str]:
        """
        Check if a scanner should actually be generated.
        Prevents duplicate generation.

        Returns:
            Tuple of (should_generate, reason).
        """
        # Extract scanner name from filename
        scanner_name = filename.replace("_scanner.py", "").replace("scanners/", "")

        # 1. Check if scanner file already exists on disk
        scanner_path = Path(f"scanners/{scanner_name}_scanner.py")
        if scanner_path.exists():
            return False, f"Scanner file '{scanner_name}_scanner.py' already exists on disk."

        # 2. Check if already generated this session (in-memory guard)
        session_key = f"scanner:{scanner_name}"
        if session_key in self._generated_this_session:
            return False, f"Scanner '{scanner_name}' was already generated this session."

        # 3. Check CEO knowledge base
        if self.ceo_kb.scanner_exists(scanner_name):
            return False, f"Scanner '{scanner_name}' already registered in knowledge base."

        if self.ceo_kb.scanner_already_tried(scanner_name):
            return False, f"Scanner '{scanner_name}' was already attempted previously."

        return True, ""

    def _generate_and_deploy_scanner(self, opportunity: Dict) -> None:
        """Generate and deploy a new scanner."""
        description = opportunity.get("description", "Add new scanner")

        # Extract potential scanner name before full generation
        desc_lower = description.lower()
        words = desc_lower.split()
        potential_name = "custom"
        for word in words:
            if word in ("for", "scanner", "scan", "new", "add", "a"):
                continue
            potential_name = word
            break
        potential_filename = f"{potential_name}_scanner.py"

        # Check if we should generate before proceeding
        should_gen, reason = self._should_generate_scanner(description, potential_filename)
        if not should_gen:
            self.notifier.send_self_improvement(
                f"⏭️ Skipping scanner generation for '{potential_name}': {reason}",
                success=True,
            )
            self.ceo_kb.record_scanner_attempt(potential_name, success=False)
            self.analyzer.record_code_generation(False)
            return

        self.notifier.send_self_improvement(
            f"Identified: {description}. Generating scanner...",
            success=True,
        )

        code, filename = self.generator.generate_feature(
            f"Add a scanner for {description}"
        )

        module_path = f"scanners.{filename.replace('.py', '')}"
        success, msg = self.deployer.deploy_code(code, filename, module_path)

        # Record the attempt in CEO knowledge base
        actual_name = filename.replace("_scanner.py", "")
        self._generated_this_session.add(f"scanner:{actual_name}")
        self.ceo_kb.record_scanner_attempt(actual_name, success=success)
        if success:
            self.ceo_kb.register_scanner(actual_name, success=True)

        self.analyzer.record_code_generation(success)

        if success:
            # Try to reload the module
            reload_success, reload_msg = self.deployer.reload_module(module_path)
            self.notifier.send_self_improvement(
                f"Generated new scanner module: {filename}. "
                f"Deployed: {msg}. Reload: {reload_msg}",
                success=True,
            )
            self.kb.add_improvement(
                feature=f"Added scanner: {filename}",
                code_changed=filename,
                success=True,
                details=msg,
            )

            # Notify engine about new scanner
            if self.engine:
                self.notifier.send_status(
                    cycle=self.engine.state.cycle,
                    duration=0,
                    keys_found=0,
                    new_scanner=filename.replace(".py", ""),
                )
        else:
            self.notifier.send_self_improvement(
                f"Scanner deployment failed: {msg}",
                success=False,
            )
            self.kb.add_failed_attempt(
                feature=f"Scanner: {filename}",
                error=msg,
            )

    def _generate_and_deploy_validator(self, opportunity: Dict) -> None:
        """Generate and deploy a new validator rule."""
        description = opportunity.get("description", "Add validation")
        self.notifier.send_self_improvement(
            f"Identified: {description}. Generating validator...",
            success=True,
        )

        code, filename = self.generator.generate_feature(
            f"Add validation for {description}"
        )

        success, msg = self.deployer.deploy_code(code, filename)
        self.analyzer.record_code_generation(success)

        if success:
            self.notifier.send_self_improvement(
                f"Validator rule added: {msg}",
                success=True,
            )
        else:
            self.notifier.send_self_improvement(
                f"Validator deployment failed: {msg}",
                success=False,
            )

    def trigger_improvement(self, description: str) -> Tuple[bool, str]:
        """
        Manually trigger a self-improvement cycle with a description.

        Args:
            description: Natural language description of the improvement.

        Returns:
            Tuple of (success, message).
        """
        self.notifier.send_self_improvement(
            f"Manual improvement triggered: {description}",
            success=True,
        )

        code, filename = self.generator.generate_feature(description)

        # Duplicate guard for scanner generation (fix add_scanner loop)
        if "scanner" in description.lower() or "scan" in description.lower():
            scanner_name = filename.replace("_scanner.py", "")
            should_gen, reason = self._should_generate_scanner(description, filename)
            # Record every attempt in knowledge base as required
            self.ceo_kb.record_scanner_attempt(scanner_name, success=False)
            if not should_gen:
                self.notifier.send_self_improvement(
                    f"⏭️ Skipping scanner generation for '{scanner_name}': {reason}",
                    success=True,
                )
                return False, reason

        # Determine deployment target
        if "scanner" in description.lower() or "scan" in description.lower():
            module_path = f"scanners.{filename.replace('.py', '')}"
            success, msg = self.deployer.deploy_code(code, filename, module_path)
            if success:
                self.deployer.reload_module(module_path)
                self.ceo_kb.register_scanner(filename.replace("_scanner.py", ""), success=True)
                self.ceo_kb.record_code_generation(description, filename, True)
            else:
                self.ceo_kb.record_code_generation(description, filename, False)
        elif "pattern" in description.lower():
            success, msg = self._deploy_pattern({"description": description})
        else:
            success, msg = self.deployer.deploy_code(code, filename)

        self.analyzer.record_code_generation(success)

        if success:
            self.kb.add_improvement(
                feature=description,
                code_changed=filename,
                success=True,
                details=msg,
            )
            self.notifier.send_self_improvement(
                f"Improvement deployed: {msg}",
                success=True,
            )
        else:
            self.kb.add_failed_attempt(
                feature=description,
                error=msg,
            )
            self.notifier.send_self_improvement(
                f"Improvement failed: {msg}",
                success=False,
            )

        return success, msg

    def get_metrics(self) -> Dict:
        """Get self-improvement metrics."""
        return {
            "metrics": self.analyzer.get_metrics(),
            "success_rate": self.analyzer.get_success_rate(),
            "improvement_history": self.kb.get_improvement_history(),
            "deployment_history": self.deployer.get_deployment_history(),
            "priority_scanners": self.analyzer.identify_priority_scanners(),
        }
