"""
Git Manager for AlphaScan v0.5.

Handles autonomous Git operations: commit, push, sync, and rollback.
"""
import logging
import os
from typing import Dict, Optional, List
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


class GitManager:
    """
    Manages autonomous Git operations for AlphaScan.

    - Commit changes with descriptive messages
    - Push to GitHub
    - Sync (pull before push)
    - Rollback to previous working state
    """

    def __init__(self, repo_path: Optional[Path] = None, auto_push: bool = True):
        self._repo_path = repo_path or Path.cwd()
        self._auto_push = auto_push
        self._repo = None
        self._commit_history: List[Dict] = []
        self._init_repo()

    def _init_repo(self) -> None:
        """Initialize the Git repository."""
        try:
            import git
            self._repo = git.Repo(str(self._repo_path))
            logger.info(f"Git repository initialized at {self._repo_path}")
        except Exception as e:
            logger.warning(f"Git repository not available: {e}")
            self._repo = None

    def is_available(self) -> bool:
        """Check if Git is available."""
        return self._repo is not None

    def commit_changes(self, message: str, auto_add: bool = True) -> Dict:
        """
        Commit changes to the repository.

        Args:
            message: Commit message.
            auto_add: Whether to automatically add all changes.

        Returns:
            Dict with commit result.
        """
        if not self._repo:
            return {"success": False, "error": "Git repository not available"}

        try:
            if auto_add:
                self._repo.git.add(A=True)

            # Check if there are changes to commit
            if not self._repo.is_dirty():
                return {"success": True, "message": "No changes to commit", "commit": None}

            # Format commit message
            full_message = f"AlphaScan: {message}\n\nGenerated by AlphaScan v0.5 autonomous system."

            # Create commit
            commit = self._repo.index.commit(full_message)

            result = {
                "success": True,
                "message": f"Committed changes: {message}",
                "commit": str(commit),
                "commit_hex": commit.hexsha,
                "timestamp": datetime.utcnow().isoformat(),
            }

            self._commit_history.append(result)
            logger.info(f"Git commit: {commit.hexsha[:8]} - {message}")

            # Auto-push if enabled
            if self._auto_push:
                push_result = self.push_to_github()
                result["push"] = push_result

            return result

        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return {"success": False, "error": str(e)}

    def push_to_github(self) -> Dict:
        """Push changes to GitHub."""
        if not self._repo:
            return {"success": False, "error": "Git repository not available"}

        try:
            # Get the current branch
            branch = self._repo.active_branch.name

            # Push to origin
            origin = self._repo.remote(name="origin")
            push_result = origin.push(branch)

            result = {
                "success": True,
                "message": f"Pushed to origin/{branch}",
                "branch": branch,
                "timestamp": datetime.utcnow().isoformat(),
            }

            logger.info(f"Git push: origin/{branch}")
            return result

        except Exception as e:
            logger.error(f"Git push failed: {e}")
            return {"success": False, "error": str(e)}

    def sync_repo(self) -> Dict:
        """Sync the repository (pull before push to avoid conflicts)."""
        if not self._repo:
            return {"success": False, "error": "Git repository not available"}

        try:
            # Pull latest changes
            origin = self._repo.remote(name="origin")
            branch = self._repo.active_branch.name

            pull_result = origin.pull(branch)

            result = {
                "success": True,
                "message": f"Synced with origin/{branch}",
                "branch": branch,
                "timestamp": datetime.utcnow().isoformat(),
            }

            logger.info(f"Git sync: origin/{branch}")
            return result

        except Exception as e:
            logger.error(f"Git sync failed: {e}")
            return {"success": False, "error": str(e)}

    def rollback(self, commit_hash: Optional[str] = None) -> Dict:
        """
        Rollback to a previous working state.

        Args:
            commit_hash: Commit hash to rollback to. If None, rolls back to previous commit.

        Returns:
            Dict with rollback result.
        """
        if not self._repo:
            return {"success": False, "error": "Git repository not available"}

        try:
            if commit_hash is None:
                # Rollback to previous commit
                commit_hash = self._repo.head.commit.parents[0].hexsha

            # Create a new commit that reverts the changes
            self._repo.git.revert(commit_hash, no_commit=True)
            self._repo.index.commit(f"AlphaScan: Rollback to {commit_hash[:8]}")

            result = {
                "success": True,
                "message": f"Rolled back to {commit_hash[:8]}",
                "commit": commit_hash,
                "timestamp": datetime.utcnow().isoformat(),
            }

            logger.info(f"Git rollback: {commit_hash[:8]}")
            return result

        except Exception as e:
            logger.error(f"Git rollback failed: {e}")
            return {"success": False, "error": str(e)}

    def get_status(self) -> Dict:
        """Get Git repository status."""
        if not self._repo:
            return {"available": False, "error": "Git repository not available"}

        try:
            return {
                "available": True,
                "branch": self._repo.active_branch.name,
                "dirty": self._repo.is_dirty(),
                "untracked_files": self._repo.untracked_files,
                "commit_history": self._commit_history[-10:],
                "latest_commit": str(self._repo.head.commit)[:8] if self._repo.head.commit else None,
            }
        except Exception as e:
            return {"available": False, "error": str(e)}

    def get_commit_history(self, limit: int = 20) -> List[Dict]:
        """Get recent commit history."""
        if not self._repo:
            return []

        commits = []
        try:
            for commit in self._repo.iter_commits(max_count=limit):
                commits.append({
                    "hash": commit.hexsha[:8],
                    "message": commit.message.strip(),
                    "author": str(commit.author),
                    "date": datetime.fromtimestamp(commit.committed_date).isoformat(),
                })
        except Exception as e:
            logger.error(f"Failed to get commit history: {e}")

        return commits
